barcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('home/', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('bars/', views.bars_index, name='index'),
    path('bars/<int:bar_id>/', views.bars_detail, name='detail'),
    path('bars/create/', views.BarCreate.as_view(), name='bars_create'),
    path('bars/<int:pk>/update', views.BarUpdate.as_view(), name='bars_update'),
    path('bars/<int:pk>/delete', views.BarDelete.as_view(), name='bars_delete'),
    path('bars/<int:bar_id>/add_rating/', views.add_rating, name='add_rating'),
    path('avaliable/', views.AvaliableList.as_view(), name='avaliable_index'),
    path('avaliable/<int:pk>/', views.AvailableDetail.as_view(), name='avaliable_detail'),
    path('avaliable/create/', views.AvaliableCreate.as_view(), name='avaliable_create'),
    path('avaliable/<int:pk>/update/', views.AvaliableUpdate.as_view(), name='avaliable_Update'),
    path('avaliable/<int:pk>/delete/', views.AvaliableDelete.as_view(), name='avaliable_delete'),
    path('bars/<int:bar_id>/assoc_bar/<int:avaliable_id>/', views.assoc_avaliable, name='assoc_avaliable'),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from datetime import date

RATING = (
    ('A', '⭐️⭐️⭐️⭐️⭐️'),
    ('B', '⭐️⭐️⭐️⭐️'),
    ('C', '⭐️⭐️⭐️'),
    ('D', '⭐️⭐️'),
    ('E', '⭐️'),
)

class Available(models.Model):
    name = models.CharField(max_length=50) 

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('available_detail', kwargs={'pk': self.id})

class Bar(models.Model):
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    address = models.CharField(max_length=100)
    menu = models.CharField(max_length=100)
    phone = models.CharField(max_length=100)
    available = models.ManyToManyField(Available)


    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('detail', kwargs={'bar_id': self.id})

class Rating(models.Model):
    date = models.DateField('rating date')
    rate = models.CharField(
        max_length=1,
        choices=RATING,
        default=RATING[0][0]
    )
    bar = models.ForeignKey(Bar, on_delete=models.CASCADE)

    def __str__(self):
    # Nice method for obtaining the friendly value of a Field.choice
        return f"{self.get_rate_display()} on {self.date}"

  # change the default sort
    class Meta:
        ordering = ['-date']

main_app/forms.py
from django.forms import ModelForm
from .models import Rating

class RatingForm(ModelForm):
  class Meta:
    model = Rating
    fields = ['date', 'rate']

main_app/views.py
from django.shortcuts import redirect, render
from django.http import HttpResponse
from .models import Bar, Available
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from .forms import RatingForm

def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

def bars_index(request):
    bars = Bar.objects.all()
    return render(request, 'bars/index.html', { 'bars': bars })

def bars_detail(request, bar_id):
    bar = Bar.objects.get(id=bar_id)
    avaliable_bar_doesnt_have = Available.objects.exclude(id__in = bar.avaliable.all().values_list('id'))
    rating_form = RatingForm()
    return render(request, 'bars/detail.html', { 'bar': bar, 'rating_form': rating_form, 'avaliable': avaliable_bar_doesnt_have })

    
class BarCreate(CreateView):
    model = Bar
    fields = '__all__'
class BarUpdate(UpdateView):
    model = Bar
    fields = '__all__'
class BarDelete(DeleteView):
    model = Bar
    success_url = '/bars/'

def add_rating(request, bar_id):
	# create the ModelForm using the data in request.POST
  form = RatingForm(request.POST)
  # validate the form
  if form.is_valid():
    # don't save the form to the db until it
    # has the cat_id assigned
    new_rating = form.save(commit=False)
    new_rating.bar_id = bar_id
    new_rating.save()
  return redirect('detail', bar_id=bar_id)

class AvaliableList(ListView):
  model = Available

class AvailableDetail(DetailView):
  model = Available

class AvaliableCreate(CreateView):
  model = Available
  fields = '__all__'

class AvaliableUpdate(UpdateView):
  model = Available
  fields = ['name']

class AvaliableDelete(DeleteView):
  model = Available
  success_url = '/avaliable/'

def assoc_avaliable(request, bar_id, avaliable_id):
  Bar.objects.get(id=bar_id).avaliable.add(avaliable_id)
  return redirect('detail', bar_id=bar_id)

main_app/templates/about.html
{% extends 'base.html' %}{% block content %}
<h1>About the Bar Collector</h1>
<hr />
<p>Hire the Bar Collector!</p>

{% endblock %}

main_app/templates/bars/detail.html
{% extends 'base.html' %} {% block content %}

<h1>Bar Details</h1>

<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ bar.name }}</span>
        <p>Description: {{ bar.description }}</p>
        <p>Address: {{ bar.address }}</p>
        <p>Menu: <a href="{{ bar.menu }}">{{ bar.menu }}</a></p>
        <p>Phone: {{ bar.phone }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'bars_update' bar.id %}">Edit</a>
        <a href="{% url 'bars_delete' bar.id %}">Delete</a>
      </div>
    </div>
  </div>
  <div class="col s6">
    <form action="{% url 'add_rating' bar.id %}" method="post">
      {% csrf_token %} {{ rating_form.as_p }}
      <input type="submit" class="btn" value="Add Rating" />
    </form>
    <br />
    <table class="striped">
      <thead>
        <tr>
          <th>Date</th>
          <th>Rate</th>
        </tr>
      </thead>
      <tbody>
        {% for rating in bar.rating_set.all %}
        <tr>
          <td>{{rating.date}}</td>
          <td>{{rating.get_rate_display}}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
<hr />
<div class="row">
  <div class="col s6">
    <h3>[{{ bar.name }}] Available</h3>
    {% if bar.available.count %} {% for available in bar.avaliable.all %}
    <div class="card">
      <div class="card-content">
        <span class="card-title"> {{ available.name }} </span>
      </div>
    </div>
    {% endfor %} {% else %}
    <h5>No Available Yet</h5>
    {% endif %}
  </div>
  <div class="col s6">
    <h3>Available</h3>
    {% if avaliable.count %} {% for available in avaliable.all %}
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{available.name}}</span>
      </div>
      <div class="card-action">
        <form
          action="{% url 'assoc_avaliable' bar.id avaliable.id %}"
          method="post"
        >
          {% csrf_token %}<button type="submit" class="btn">Add</button>
        </form>
      </div>
    </div>
    {% endfor %} {% else %}
    <h5>None</h5>
    {% endif %}
  </div>
  <script>
    var dateEl = document.getElementById("id_date");
    M.Datepicker.init(dateEl, {
      format: "yyyy-mm-dd",
      defaultDate: new Date(),
      setDefaultDate: true,
      autoClose: true,
    });
    var selectEl = document.getElementById("id_rate");
    M.FormSelect.init(selectEl);
  </script>
  {% endblock %}
</div>

main_app/templates/bars/index.html
{% extends 'base.html' %} {% block content %}

<h1>Bar List</h1>

{% for bar in bars %}
<div class="card">
    <a href="{% url 'detail' bar.id %}">
    <div class="card-content">
      <span class="card-title">{{ bar.name }}</span>
    </div>
  </div>
</a>
{% endfor %} {% endblock %}

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Bar Collector</title>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'css/style.css' %}"
    />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  </head>
  <body>
    <header class="navbar-fixed">
      <nav>
        <div class="nav-wrapper">
          <ul>
            <li>
              <a href="/home" class="left brand-logo"
                >&nbsp;&nbsp;BarCollector</a
              >
            </li>
          </ul>
          <ul class="right">
            <li><a href="{% url 'about' %}">About</a></li>
            <li><a href="{% url 'avaliable_create' %}">Bar Avaliable</a></li>
            <li>
              <a href="{% url 'bars_create' %}">Add your favourite Bar</a>
            </li>
            <li><a href="{% url 'index' %}">View All Bars</a></li>
          </ul>
        </div>
      </nav>
    </header>
    <main class="container">{% block content %} {% endblock %}</main>
    <footer class="page-footer">
      <div class="right">
        All Rights Reserved, &copy; 2022 Bar Collector &nbsp;
      </div>
    </footer>
  </body>
</html>

main_app/templates/home.html
{% extends 'base.html' %} {% block content %}
<h1>what's popping this is home page</h1>
{% endblock %}

main_app/templates/main_app/avaliable_detail.html
{% extends 'base.html' %} {% block content %}

<h1>Avaliable Details</h1>

<div class="row">
  <div class="col s6 col-offset-3">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ avaliable.name }}</span>
      </div>
      <div class="card-action">
        <a href="{% url 'avaliable_update' avaliable.id %}">Edit</a>
        <a href="{% url 'avaliable_delete' avaliable.id %}">Delete</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

main_app/templates/main_app/avaliable_form.html
{% extends 'base.html' %} {% block content %} {% if object %}
<h1>Edit <span class="teal-text">{{object.name}}</span></h1>
{% else %}
<h1>Add Available</h1>
{% endif %}
<!-- Leaving the action empty makes the form post to the same url used to display it -->
<form action="" method="post">
  <!-- Django requires the following for security purposes -->
  {% csrf_token %}
  <!-- Render the inputs inside of <tr>s & <td>s -->
  {{ form.as_table }}
  <input type="submit" value="Submit!" class="btn" />
</form>
{% endblock %}

main_app/templates/main_app/avaliable_list.html
{% extends 'base.html' %} {% block content %}

<h1>Available List</h1>

{% for available in avaliable_list %}
<a href="{% url 'avaliable_detail' avaliable.id %}">
  <div class="card">
    <div class="card-content">
      <span class="card-title">{{ avaliable.name }}</span>
    </div>
  </div>
</a>
{% endfor %} {% endblock %}

main_app/templates/main_app/bar_confirm_delete.html
{% extends 'base.html' %} {% block content %}
<h1>Delete Bar</h1>

<h4>
  Are you sure you want to delete
  <span class="teal-text">{{ object.name }}</span>?
</h4>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes - Delete!" class="btn" />
  <a href="{% url 'detail' bar.id %}">Cancel</a>
</form>
{% endblock %}

main_app/templates/main_app/bar_form.html
{% extends 'base.html' %} {% block content %} {% if object %}
<h1>Edit <span class="teal-text">{{object.name}}</span></h1>
{% else %}
<h1>Add Your Bar</h1>
{% endif %}
<form action="" method="POST">
  {% csrf_token %} {{ form }}
  <input type="submit" value="Submit" class="btn" />
</form>

{% endblock %}